apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  labels:
    app: echo-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: echo-server
        image: umemurayuga/echo-server:v1
        ports:
        - containerPort: 1323
